"""
Task-level schema: the Synthesis phase turns a ComprehensionResult into a
list of MigrationTask objects. These are the unit the parallel editor
fanout (LangGraph `Send()`) operates on — one task per Send.
"""

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, Field

from app.graph.state.enums import TaskStatus, TestOutcome


class TargetFileSpec(BaseModel):
    """One file the editor is expected to produce for a task."""

    path: str = Field(description="Path relative to target repo root, e.g. 'app/routers/orders.py'")
    purpose: str


class MigrationTask(BaseModel):
    id: str = Field(description="Stable id, e.g. 'task::endpoint::create_order'")
    source_unit_ids: list[str] = Field(
        description="SemanticUnit id(s) from the IR this task migrates. Usually 1, sometimes many "
        "(e.g. several PHP includes collapsing into one Next.js page)."
    )
    target_files: list[TargetFileSpec] = Field(
        description="Expected output file(s). Can be >1 (e.g. one Angular service -> React hook + context)."
    )
    depends_on_task_ids: list[str] = Field(default_factory=list)
    synthesis_instructions: str = Field(
        description="Concrete, target-stack-specific instructions generated by Synthesis for the editor node. "
        "This is where 'Spring @RestController -> FastAPI APIRouter' type mapping decisions live."
    )
    status: TaskStatus = TaskStatus.PENDING
    retry_count: int = 0
    max_retries: int = 3


class FileDiff(BaseModel):
    path: str
    content: str = Field(description="Full file content (not a unified diff) — simpler to apply, review, and test")
    is_new_file: bool = True


class EditorResult(BaseModel):
    task_id: str
    diffs: list[FileDiff]
    editor_notes: str = Field(default="", description="Assumptions or caveats the editor agent wants surfaced")
    tokens_used: int = 0
    produced_at: datetime = Field(default_factory=datetime.utcnow)


class TestResult(BaseModel):
    task_id: str | None = Field(
        default=None, description="None for a full-suite run after aggregation, set for a scoped per-task run"
    )
    outcome: TestOutcome
    raw_output: str = Field(description="stdout/stderr from the test runner, truncated to a sane length upstream")
    failing_tests: list[str] = Field(default_factory=list)
    duration_seconds: float = 0.0


class ErrorAnalysis(BaseModel):
    task_id: str
    root_cause_summary: str
    is_retryable: bool
    suggested_fix_instructions: str | None = Field(
        default=None, description="Fed back into the editor node's next attempt as extra context"
    )
    requires_replan: bool = Field(
        default=False, description="True if the fix needs a different task decomposition, not just a retry"
    )
