"""
Aggregation node.

Runs once the full suite has passed (routed here by SANDBOX_PASSED).
Takes the run's *effective* output (app/graph/diffs.py — the same
function the sandbox used, so what's aggregated is exactly what was
tested) and produces a PRDraft: a title, body, branch name, and commit
message, deterministically — no LLM call. A PR description is
structured, factual content (what changed, what stack, what ambiguities
remain); generating it with an LLM would add cost and a source of
flakiness for no real benefit over a template, so this stays templated
on purpose.

Path safety is checked a SECOND time here (the editor node's file-contract
check in Step 6's earlier hardening already constrains output paths to a
task's declared target_files, and those come from a trusted adapter) —
belt-and-suspenders before anything is queued to reach a real repository.
Any violation here is a hard stop, not a silent drop: dropping a file
from a migration without saying so is worse than refusing to proceed.
"""

from __future__ import annotations

from app.graph.diffs import effective_diffs, effective_results
from app.graph.state import ComprehensionResult, EditorResult, FileDiff, MigrationPhase, MigrationTask, PRDraft
from app.vcs.paths import publishable_path_problem


def _build_pr_draft(
    *,
    config: dict,
    diffs: list[FileDiff],
    results: list[EditorResult],
    tasks: list[MigrationTask],
    comprehension: ComprehensionResult | None,
) -> PRDraft:
    run_id = config["run_id"]
    branch_name = f"stackmigrate/{run_id}"
    title = f"Migrate {config['scope_description']} ({config['source_stack']} \u2192 {config['target_stack']})"

    tasks_by_id = {t.id: t for t in tasks}
    lines = [
        f"Automated migration from **{config['source_stack']}** to **{config['target_stack']}**.",
        "",
        f"Scope: {config['scope_description']}",
        "",
        "## Files changed",
    ]
    for result in results:
        task = tasks_by_id.get(result.task_id)
        purpose = task.target_files[0].purpose if task and task.target_files else ""
        for diff in result.diffs:
            suffix = f" — {purpose}" if purpose else ""
            lines.append(f"- `{diff.path}`{suffix}")

    if comprehension and comprehension.unresolved_ambiguities:
        lines += ["", "## Flagged for review", "The migration analysis noted the following — please check these:"]
        for note in comprehension.unresolved_ambiguities[:15]:  # bounded: this is a PR body, not a full log
            lines.append(f"- {note}")
        if len(comprehension.unresolved_ambiguities) > 15:
            lines.append(f"- ...and {len(comprehension.unresolved_ambiguities) - 15} more (see full run log).")

    lines += ["", "---", "*Generated by stackmigrate. All test suites passed before this PR was opened. Please review before merging.*"]

    return PRDraft(
        title=title,
        body="\n".join(lines),
        branch_name=branch_name,
        commit_message=f"stackmigrate: {title}",
    )


def build_aggregate_node():
    async def aggregate_node(state: dict) -> dict:
        tasks = state.get("tasks", [])
        editor_results = state.get("editor_results", [])
        comprehension = state.get("comprehension")
        config = state["config"]

        results = effective_results(editor_results, tasks)
        diffs = effective_diffs(editor_results, tasks)

        if not diffs:
            return {
                "phase": MigrationPhase.FAILED,
                "error_log": ["Aggregation found zero effective diffs despite a passing sandbox run — nothing to ship."],
            }

        problems = [(d.path, publishable_path_problem(d.path)) for d in diffs]
        problems = [(p, reason) for p, reason in problems if reason]
        if problems:
            return {
                "phase": MigrationPhase.FAILED,
                "error_log": [f"Refusing to aggregate — unpublishable path '{p}': {reason}" for p, reason in problems],
            }

        draft = _build_pr_draft(config=config, diffs=diffs, results=results, tasks=tasks, comprehension=comprehension)

        return {
            "aggregated_diff_paths": [d.path for d in diffs],
            "pr_draft": draft,
            "phase": MigrationPhase.AGGREGATING,
        }

    return aggregate_node
